# The Vulkan backend's shader list. Each entry is "name|source|glslc defines"
# (defines space-separated); every entry becomes a ShaderId::<name> in the
# generated shader_table.h and an embedded SPIR-V blob. Sources are in this
# directory and may #include anything else here (common.glsl, op_codes.h).
#
# Dtype families are listed as consecutive <base>_f32, <base>_f16, <base>_bf16
# entries and named in kDtypeFamilies (detail/kernels.h), which picks a variant
# by offsetting from the _f32 id; register.cpp checks the order at start-up.

set(BROTENSOR_VK_SHADERS
    "unary_f32|unary.comp|-DDT=0"
    "unary_f16|unary.comp|-DDT=1"
    "unary_bf16|unary.comp|-DDT=2"
    "binary_f32|binary.comp|-DDTY=0 -DDTX=0"
    "binary_f16|binary.comp|-DDTY=1 -DDTX=1"
    "binary_bf16|binary.comp|-DDTY=2 -DDTX=2"
    "binary_f32_f16|binary.comp|-DDTY=0 -DDTX=1"
    "act_bwd_f32|act_bwd.comp|-DDT=0"
    "act_bwd_f16|act_bwd.comp|-DDT=1"
    "act_bwd_bf16|act_bwd.comp|-DDT=2"
    "bias_f32|bias.comp|-DDT=0"
    "bias_f16|bias.comp|-DDT=1"
    "bias_bf16|bias.comp|-DDT=2"
    "cast_f32_to_f16|cast.comp|-DSDT=0 -DDDT=1"
    "cast_f32_to_bf16|cast.comp|-DSDT=0 -DDDT=2"
    "cast_f16_to_f32|cast.comp|-DSDT=1 -DDDT=0"
    "cast_f16_to_bf16|cast.comp|-DSDT=1 -DDDT=2"
    "cast_bf16_to_f32|cast.comp|-DSDT=2 -DDDT=0"
    "cast_bf16_to_f16|cast.comp|-DSDT=2 -DDDT=1"
    "sum_rows_f32|reduce_rows.comp|-DDT=0 -DREDUCE_SUM"
    "sum_rows_f16|reduce_rows.comp|-DDT=1 -DREDUCE_SUM"
    "sum_rows_bf16|reduce_rows.comp|-DDT=2 -DREDUCE_SUM"
    "argmax_rows_f32|reduce_rows.comp|-DDT=0 -DREDUCE_ARGMAX"
    "argmax_rows_f16|reduce_rows.comp|-DDT=1 -DREDUCE_ARGMAX"
    "argmax_rows_bf16|reduce_rows.comp|-DDT=2 -DREDUCE_ARGMAX"
    "sum_cols_f32|sum_cols.comp|-DDT=0"
    "sum_cols_f16|sum_cols.comp|-DDT=1"
    "sum_cols_bf16|sum_cols.comp|-DDT=2"
    "copy2d_b1|copy2d.comp|-DES=1"
    "copy2d_b2|copy2d.comp|-DES=2"
    "copy2d_b4|copy2d.comp|-DES=4"
    "transpose_b2|transpose.comp|-DES=2"
    "transpose_b4|transpose.comp|-DES=4"
    "fill_bytes|fill_bytes.comp|"
    "gemm_cm_f16|gemm_cm.comp|-DDT=1"
    "gemm_cm_bf16|gemm_cm.comp|-DDT=2"
    "gemm_simt_f32|gemm_simt.comp|-DDTA=0 -DDTB=0 -DDTC=0"
    "gemm_simt_f16|gemm_simt.comp|-DDTA=1 -DDTB=1 -DDTC=1"
    "gemm_simt_bf16|gemm_simt.comp|-DDTA=2 -DDTB=2 -DDTC=2"
    "gemm_simt_f32_w16|gemm_simt.comp|-DDTA=0 -DDTB=1 -DDTC=0"
    "gemm_simt_f32_wbf16|gemm_simt.comp|-DDTA=0 -DDTB=2 -DDTC=0"
    "gemm_simt_f16_c32|gemm_simt.comp|-DDTA=1 -DDTB=1 -DDTC=0 -DDTBI=1"
    "gemm_simt_bf16_c32|gemm_simt.comp|-DDTA=2 -DDTB=2 -DDTC=0 -DDTBI=2"
    "gemv_f32|gemv.comp|-DDTX=0 -DDTW=0 -DDTY=0"
    "gemv_f16|gemv.comp|-DDTX=1 -DDTW=1 -DDTY=1"
    "gemv_bf16|gemv.comp|-DDTX=2 -DDTW=2 -DDTY=2"
    "gemv_f32_w16|gemv.comp|-DDTX=0 -DDTW=1 -DDTY=0"
    "gemv_f32_wbf16|gemv.comp|-DDTX=0 -DDTW=2 -DDTY=0"
    "glu_f32|glu.comp|-DDT=0 -DDTY=0"
    "glu_f16|glu.comp|-DDT=1 -DDTY=1"
    "glu_bf16|glu.comp|-DDT=2 -DDTY=2"
    "glu_f32_to_f16|glu.comp|-DDT=0 -DDTY=1"
    "glu_f32_to_bf16|glu.comp|-DDT=0 -DDTY=2"
    "norm_f32|norm.comp|-DDTX=0 -DDTY=0 -DDTG=0"
    "norm_f16|norm.comp|-DDTX=1 -DDTY=1 -DDTG=1"
    "norm_bf16|norm.comp|-DDTX=2 -DDTY=2 -DDTG=2"
    "norm_f16_g32|norm.comp|-DDTX=1 -DDTY=1 -DDTG=0"
    "norm_bf16_g32|norm.comp|-DDTX=2 -DDTY=2 -DDTG=0"
    "norm_f32_y16|norm.comp|-DDTX=0 -DDTY=1 -DDTG=0"
    "rope_f32|rope.comp|-DDT=0"
    "rope_f16|rope.comp|-DDT=1"
    "rope_bf16|rope.comp|-DDT=2"
    "rowvec_f32|rowvec.comp|-DDT=0"
    "rowvec_f16|rowvec.comp|-DDT=1"
    "rowvec_bf16|rowvec.comp|-DDT=2"
    "fa_cm_f16|fa_cm.comp|-DDT=1"
    "fa_cm_bf16|fa_cm.comp|-DDT=2"
    "fa_rows_f32|fa_rows.comp|-DDT=0"
    "fa_rows_f16|fa_rows.comp|-DDT=1"
    "fa_rows_bf16|fa_rows.comp|-DDT=2"
    "fa_combine_f32|fa_combine.comp|-DDT=0"
    "fa_combine_f16|fa_combine.comp|-DDT=1"
    "fa_combine_bf16|fa_combine.comp|-DDT=2"
    "attn_softmax_f32|attn_softmax.comp|-DDTP=0"
    "attn_softmax_f16|attn_softmax.comp|-DDTP=1"
    "attn_softmax_bf16|attn_softmax.comp|-DDTP=2"
    "attn_aux_f32|attn_aux.comp|-DDT=0"
    "attn_aux_f16|attn_aux.comp|-DDT=1"
    "attn_aux_bf16|attn_aux.comp|-DDT=2"
    "topk_seg_f32|topk_seg.comp|-DDT=0"
    "topk_seg_f16|topk_seg.comp|-DDT=1"
    "topk_seg_bf16|topk_seg.comp|-DDT=2"
    "xent|xent.comp|"
    "conv_cm_f16|conv_cm.comp|-DDT=1"
    "conv_cm_bf16|conv_cm.comp|-DDT=2"
    "conv_simt_f32|conv_simt.comp|-DDT=0"
    "conv_simt_f16|conv_simt.comp|-DDT=1"
    "conv_simt_bf16|conv_simt.comp|-DDT=2"
    "conv_direct_f32|conv_direct.comp|-DDT=0"
    "conv_direct_f16|conv_direct.comp|-DDT=1"
    "conv_direct_bf16|conv_direct.comp|-DDT=2"
    "resample_f32|resample.comp|-DDT=0"
    "resample_f16|resample.comp|-DDT=1"
    "resample_bf16|resample.comp|-DDT=2"
    "remap_b2|remap.comp|-DES=2"
    "remap_b4|remap.comp|-DES=4"
    "gnorm_f32|gnorm.comp|-DDT=0"
    "gnorm_f16|gnorm.comp|-DDT=1"
    "gnorm_bf16|gnorm.comp|-DDT=2"
    "sampler_f32|sampler.comp|-DDT=0"
    "sampler_f16|sampler.comp|-DDT=1"
    "sampler_bf16|sampler.comp|-DDT=2"
    "philox|philox.comp|"
    "gemv_q_f16|gemv_q.comp|-DDT=1"
    "gemv_q_bf16|gemv_q.comp|-DDT=2"
    "dequant|dequant.comp|"
    "audio_f32|audio.comp|-DDT=0"
    "audio_f16|audio.comp|-DDT=1"
    "audio_bf16|audio.comp|-DDT=2"
    "dft|dft.comp|-DDT=0"
    "select|select.comp|-DDT=0"
    "test_shared_overflow|test_shared_overflow.comp|"
)
