#pragma once

// ─── Brass CUDA Driver JIT runtime bridge for brotensor ──────────────────────
//
// Dynamically compiles and launches high-performance PTX kernels generated by
// Brass (`libbrass`) using the CUDA Driver API on NVIDIA RTX GPUs (sm_89).
// Bypasses CUDA runtime compiler overhead with CU_JIT_OPTIMIZATION_LEVEL = 4,
// achieving zero GC overhead and 128-bit vector memory bandwidth.

#include <cstdint>
#include <cstddef>

namespace brotensor::detail::cuda::jit {

// Checks whether CUDA Driver JIT compiler and RTX GPU are initialized and available.
bool is_cuda_jit_available();

// Launches parallel PTX kernel for Fused Residual RMSNorm:
// Updates X in-place (X += res), accumulates sum_sq in registers,
// computes cooperative warp-shuffle RMSNorm, writes Y = X * gamma * rrms.
void launch_fused_residual_rmsnorm_ptx(
    float* X,
    const float* res,
    const float* gamma,
    float* Y,
    int B,
    int D,
    float eps = 1e-5f,
    void* stream = nullptr
);

// Launches parallel PTX kernel for Fused LayerNorm + AdaLN Modulate:
// Cooperatively computes LayerNorm mean & variance, applies modulate (1 + scale) + shift
// directly into Y in registers with zero intermediate DRAM writes.
void launch_fused_layernorm_modulate_ptx(
    const float* X,
    const float* gamma,
    const float* beta,
    const float* scale,
    const float* shift,
    float* Y,
    int R,
    int D,
    float eps = 1e-5f,
    void* stream = nullptr
);

// Launches parallel PTX kernel for SwiGLU:
// Elementwise grid-strided 128-bit vector kernel (v4.f32) with fast ex2.approx.f32 SiLU.
void launch_swiglu_ptx(
    const float* X,
    float* Y,
    int B,
    int D,
    void* stream = nullptr
);

// Launches parallel PTX kernel for AdaLN Modulate:
// Elementwise grid-strided 128-bit vector kernel (v4.f32) across feature dimension D.
void launch_modulate_ptx(
    const float* X,
    const float* scale,
    const float* shift,
    float* Y,
    int L,
    int D,
    void* stream = nullptr
);

} // namespace brotensor::detail::cuda::jit
