#pragma once

// ─── Brass CUDA Driver JIT runtime bridge for brotensor ──────────────────────
//
// Dynamically compiles and launches high-performance PTX kernels generated by
// Brass (`libbrass`) using the CUDA Driver API on NVIDIA RTX GPUs (sm_89).
// Bypasses CUDA runtime compiler overhead with CU_JIT_OPTIMIZATION_LEVEL = 4,
// achieving zero GC overhead and 128-bit vector memory bandwidth.

#include <cstdint>
#include <cstddef>

namespace brotensor::detail::cuda::jit {

// Checks whether CUDA Driver JIT compiler and RTX GPU are initialized and available.
bool is_cuda_jit_available();

// Launches parallel PTX kernel for Fused Residual RMSNorm:
// Updates X in-place (X += res), accumulates sum_sq in registers,
// computes cooperative warp-shuffle RMSNorm, writes Y = X * gamma * rrms.
void launch_fused_residual_rmsnorm_ptx(
    float* X,
    const float* res,
    const float* gamma,
    float* Y,
    int B,
    int D,
    float eps = 1e-5f,
    void* stream = nullptr
);

// Launches parallel PTX kernel for Fused Residual LayerNorm:
// Updates X in-place (X += res), cooperatively computes mean & variance,
// writes Y = ((X - mean) * rstd) * gamma + beta directly in registers.
void launch_fused_residual_layernorm_ptx(
    float* X,
    const float* res,
    const float* gamma,
    const float* beta,
    float* Y,
    int B,
    int D,
    float eps = 1e-5f,
    void* stream = nullptr
);

// Launches parallel PTX kernel for Fused LayerNorm + AdaLN Modulate:
// Cooperatively computes LayerNorm mean & variance, applies modulate (1 + scale) + shift
// directly into Y in registers with zero intermediate DRAM writes.
void launch_fused_layernorm_modulate_ptx(
    const float* X,
    const float* gamma,
    const float* beta,
    const float* scale,
    const float* shift,
    float* Y,
    int R,
    int D,
    float eps = 1e-5f,
    void* stream = nullptr
);

// Launches parallel PTX kernel for SwiGLU:
// Elementwise grid-strided 128-bit vector kernel (v4.f32) with fast ex2.approx.f32 SiLU.
void launch_swiglu_ptx(
    const float* X,
    float* Y,
    int B,
    int D,
    void* stream = nullptr
);

// Launches parallel PTX kernel for AdaLN Modulate:
// Elementwise grid-strided 128-bit vector kernel (v4.f32) across feature dimension D.
void launch_modulate_ptx(
    const float* X,
    const float* scale,
    const float* shift,
    float* Y,
    int L,
    int D,
    void* stream = nullptr
);

// Launches parallel PTX kernel for elementwise division: Y[i] /= X[i]
void launch_elementwise_div_ptx(
    float* Y,
    const float* X,
    int n,
    void* stream = nullptr
);

// Launches parallel PTX kernel for Fused GEMV SwiGLU:
// Single-token decode (M=1): computes dot products with Gate and Up weight matrices (N x K),
// warp-shuffle reduction, fast in-register SiLU(gate) * up, and stores directly to Y.
void launch_fused_gemv_swiglu_ptx(
    const float* W_gate,
    const float* W_up,
    const float* x,
    float* y,
    int N,
    int K,
    void* stream = nullptr
);

// Launches parallel PTX kernel for Fused GEMV Residual:
// Single-token decode (M=1): computes dot product with Down weight matrix (N x K),
// adds residual directly in registers, and stores to Y.
void launch_fused_gemv_residual_ptx(
    const float* W_down,
    const float* x,
    const float* res,
    float* y,
    int N,
    int K,
    void* stream = nullptr
);

// Launches parallel PTX kernel for Fused Q8_0 GEMV:
// Single-token decode (M=1): computes dot product with Q8_0 weight matrix (N x K),
// dequantizes weights in registers, and multiplies by FP32 activation vector x.
void launch_fused_gemv_q8_0_ptx(
    const void* W_q8_0,
    const float* x,
    float* y,
    int N,
    int K,
    void* stream = nullptr
);

// Launches parallel PTX kernel for Fused Q4_K GEMV:
// Single-token decode (M=1): computes dot product with Q4_K weight matrix (N x K),
// unpacks 4-bit nibbles, applies affine sub-block scaling/min in registers,
// and multiplies by FP32 activation vector x.
void launch_fused_gemv_q4_k_ptx(
    const void* W_q4_k,
    const float* x,
    float* y,
    int N,
    int K,
    void* stream = nullptr
);

} // namespace brotensor::detail::cuda::jit


